### ISSUE TITLE
Webview Allow Camera Access is not working.

### ISSUE THREAD

**Issue by vikivyas** [rekire/flutter-plugins-fork#132]
E/chromium( 8868): [ERROR:web_contents_delegate.cc(239)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.

**Comment by vikivyas** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/16920183/218032408-19606aa9-24f3-4834-8e97-0340a7ab2fb2.png">

<img width="345" alt="image" src="https://user-images.githubusercontent.com/16920183/218032640-91a1c6a6-01d6-409e-a3c9-2829eb0d61e7.png">

**Comment by rekire** [comment]
This seems not really be to related, this looks like you would use the stripe payment sdk (without using Google, just guessing)...
I would say you need to declare the camera permission in your `AndroidManifest.xml` something like this:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.CAMERA" />
</manifest>
```

**Comment by rekire** [comment]
My fork is more or less about to detect that the camera permission is not given and to hide the option to use the camera. It is not about to enable it

**Comment by vikivyas** [comment]
> This seems not really be to related, this looks like you would use the stripe payment sdk (without using Google, just guessing)... I would say you need to declare the camera permission in your `android/src/main/AndroidManifest.xml` something like this:
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
>     <uses-permission android:name="android.permission.CAMERA" />
> </manifest>
> ```

I am using strip in webview, not stripe payment sdk, &  <uses-permission android:name="android.permission.CAMERA" /> is declared in `android/src/main/AndroidManifest.xml` .

<img width="704" alt="image" src="https://user-images.githubusercontent.com/16920183/218040740-896b5a45-c702-45b8-a1dc-5e2eaff3e909.png">

**Comment by vikivyas** [comment]
> My fork is more or less about to detect that the camera permission is not given and to **hide** the option to use the camera. It is not about to enable it.

I am telling that webview is not able to detect that the camera permission is already given or not to app (in my case already given).

<img width="296" alt="image" src="https://user-images.githubusercontent.com/16920183/218041054-4c96394b-233d-4fa6-87e0-78ed07fe13ce.png">

**Comment by rekire** [comment]
That is actually interesting, I would expect that it would work in that case. I can check it might be this weekend

**Comment by vikivyas** [comment]
I wanted to follow up on the issue we discussed and wanted to check if you had a chance to look into it over the weekend. If you have any updates or need any additional information from my end, please let me know.

**Comment by rekire** [comment]
I can confirm that it is a bit tricky to make the camera working in the webview. I had not enough time to make it working. But that is not related with my changes. You can try this answer from [StackOveflow](https://stackoverflow.com/a/59080641/995926). To be honest I could also imagine that this is not supported at all yet.
